directories:
  output: release
  buildResources: build
appId: com.kinetix.controlcenter
productName: Kinetix Control Center
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
asar: true
compression: maximum
win:
  target: portable
  icon: public/favicon.ico
extraResources:
  - from: ../pc-server/dist/server.exe
    to: server.exe
  - from: ../pc-server/plugins
    to: plugins
    filter:
      - '**/*'
electronVersion: 40.7.0
