directories:
  output: release
  buildResources: build
appId: com.kinetix.controlcenter
productName: Kinetix Control Center
asar: true
compression: maximum
win:
  target: dir
  icon: public/favicon.ico
extraResources:
  - from: ../pc-server/dist/server.exe
    to: server.exe
  - from: ../pc-server/plugins
    to: plugins
    filter:
      - '**/*'
files: []
electronVersion: 40.7.0
